name = "rss-telegram-bot"
main = "src/index.js"
compatibility_date = "2024-01-01"

# D1数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "rss-bot-db"
database_id = "your-database-id-here"

# 环境变量
[vars]
TELEGRAM_BOT_TOKEN = "your-bot-token-here"

# Cron触发器 (每10分钟检查一次RSS)
[triggers]
crons = ["*/10 * * * *"]
